image: archlinux
packages:
  - git
  - wget
sources:
  - https://git.sr.ht/~ddavis/twaml
secrets:
  - a7bb07f9-3681-4e7e-8650-e49e3ca8c822
tasks:
  - setup: |
      wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
      conda config --set always_yes yes --set changeps1 no
      conda create -q -n testenv python=3.6 hdf5 setuptools numpy scipy matplotlib pytables pandas scikit-learn
      source activate testenv
      pip install pip -U
      pip install setuptools -U
      pip install "uproot>=3.0"
      pip install pytest
  - test: |
      cd twaml
      export PATH="$HOME/miniconda/bin:$PATH"
      source activate testenv
      pip install .
      pytest
  - publish: |
      cd twaml
      export PATH="$HOME/miniconda/bin:$PATH"
      source activate testenv
      pip install setuptools -U
      pip install twine
      python setup.py sdist bdist_wheel
      ls -lh dist
      python .ci-scripts/srht-pypi.py
triggers:
  - action: email
    condition: failure
    to: "<ddavis@ddavis.io>"
