image: archlinux
packages:
  - python
  - python-pip
  - python-setuptools
  - python-matplotlib
  - python-numpy
  - python-pandas
  - python-pytables
  - python-h5py
  - python-pytest
  - python-lz4
  - python-scikit-learn
  - python-wheel
  - hdf5
  - twine
sources:
  - https://github.com/drdavis/twaml
secrets:
  - a7bb07f9-3681-4e7e-8650-e49e3ca8c822
tasks:
  - setup: |
      sudo pip install uproot
  - build: |
      pwd
      cd twaml
      sudo pip install .
      pytest
  - publish: |
      cd twaml
      python setup.py sdist bdist_wheel
      ls -lh dist
      python .ci-scripts/srht-pypi.py
triggers:
  - action: email
    condition: failure
    to: "<ddavis@ddavis.io>"
